/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_affiche_nada (void)
{
  GtkWidget *affiche_nada;
  GtkWidget *fixed1;
  GtkWidget *treeview_nada;
  GtkObject *spinbuttonjaffich_adj;
  GtkWidget *spinbuttonjaffich;
  GtkObject *spinbuttonmaffich_adj;
  GtkWidget *spinbuttonmaffich;
  GtkObject *spinbuttonaaffich_adj;
  GtkWidget *spinbuttonaaffich;
  GtkWidget *btnretourm;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *vseparator1;
  GtkWidget *gotoajnada;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *gotomadifnada;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *gotosuppr;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label10;
  GtkWidget *cherchercrenau;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label13;
  GtkWidget *label11;
  GtkWidget *comboboxentryafffichnada;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *chercher_nada;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *resultatrecherchecrenau;
  GtkWidget *hseparator1;
  GtkWidget *resultatcherchelab;
  GtkWidget *actutreenada;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label48;

  affiche_nada = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affiche_nada), _("Afficher cr\303\251neau horaire"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (affiche_nada), fixed1);

  treeview_nada = gtk_tree_view_new ();
  gtk_widget_show (treeview_nada);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview_nada, 0, 72);
  gtk_widget_set_size_request (treeview_nada, 1520, 232);

  spinbuttonjaffich_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjaffich = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjaffich_adj), 1, 0);
  gtk_widget_show (spinbuttonjaffich);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonjaffich, 72, 384);
  gtk_widget_set_size_request (spinbuttonjaffich, 60, 27);

  spinbuttonmaffich_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmaffich = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmaffich_adj), 1, 0);
  gtk_widget_show (spinbuttonmaffich);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonmaffich, 192, 384);
  gtk_widget_set_size_request (spinbuttonmaffich, 60, 27);

  spinbuttonaaffich_adj = gtk_adjustment_new (1970, 1970, 2024, 1, 10, 10);
  spinbuttonaaffich = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonaaffich_adj), 1, 0);
  gtk_widget_show (spinbuttonaaffich);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonaaffich, 304, 384);
  gtk_widget_set_size_request (spinbuttonaaffich, 60, 27);

  btnretourm = gtk_button_new ();
  gtk_widget_show (btnretourm);
  gtk_fixed_put (GTK_FIXED (fixed1), btnretourm, 24, 472);
  gtk_widget_set_size_request (btnretourm, 88, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (btnretourm), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 208, 408);
  gtk_widget_set_size_request (vseparator1, 16, 16);

  gotoajnada = gtk_button_new ();
  gtk_widget_show (gotoajnada);
  gtk_fixed_put (GTK_FIXED (fixed1), gotoajnada, 352, 472);
  gtk_widget_set_size_request (gotoajnada, 88, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (gotoajnada), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  gotomadifnada = gtk_button_new ();
  gtk_widget_show (gotomadifnada);
  gtk_fixed_put (GTK_FIXED (fixed1), gotomadifnada, 624, 472);
  gtk_widget_set_size_request (gotomadifnada, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (gotomadifnada), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  gotosuppr = gtk_button_new ();
  gtk_widget_show (gotosuppr);
  gtk_fixed_put (GTK_FIXED (fixed1), gotosuppr, 976, 472);
  gtk_widget_set_size_request (gotosuppr, 104, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (gotosuppr), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  cherchercrenau = gtk_button_new ();
  gtk_widget_show (cherchercrenau);
  gtk_fixed_put (GTK_FIXED (fixed1), cherchercrenau, 1032, 424);
  gtk_widget_set_size_request (cherchercrenau, 248, 24);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (cherchercrenau), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox6), label13, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("les creneau horaire"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 808, 384);
  gtk_widget_set_size_request (label11, 208, 16);

  comboboxentryafffichnada = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryafffichnada);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxentryafffichnada, 1048, 376);
  gtk_widget_set_size_request (comboboxentryafffichnada, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryafffichnada), _("9h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryafffichnada), _("11h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryafffichnada), _("13h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryafffichnada), _("14h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryafffichnada), _("15h"));

  label1 = gtk_label_new (_("Chercher par Date render-vous :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 72, 352);
  gtk_widget_set_size_request (label1, 232, 24);

  label2 = gtk_label_new (_("jour:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 384);
  gtk_widget_set_size_request (label2, 41, 17);

  label3 = gtk_label_new (_("Mois:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 144, 384);
  gtk_widget_set_size_request (label3, 41, 17);

  label4 = gtk_label_new (_("Annee:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 256, 384);
  gtk_widget_set_size_request (label4, 41, 17);

  chercher_nada = gtk_button_new ();
  gtk_widget_show (chercher_nada);
  gtk_fixed_put (GTK_FIXED (fixed1), chercher_nada, 72, 424);
  gtk_widget_set_size_request (chercher_nada, 224, 24);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (chercher_nada), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  resultatrecherchecrenau = gtk_label_new ("");
  gtk_widget_show (resultatrecherchecrenau);
  gtk_fixed_put (GTK_FIXED (fixed1), resultatrecherchecrenau, 1240, 376);
  gtk_widget_set_size_request (resultatrecherchecrenau, 280, 24);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 0, 320);
  gtk_widget_set_size_request (hseparator1, 1520, 16);

  resultatcherchelab = gtk_label_new ("");
  gtk_widget_show (resultatcherchelab);
  gtk_fixed_put (GTK_FIXED (fixed1), resultatcherchelab, 352, 352);
  gtk_widget_set_size_request (resultatcherchelab, 264, 32);

  actutreenada = gtk_button_new ();
  gtk_widget_show (actutreenada);
  gtk_fixed_put (GTK_FIXED (fixed1), actutreenada, 712, 24);
  gtk_widget_set_size_request (actutreenada, 104, 24);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (actutreenada), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox14), label48, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_nada, "row_activated",
                    G_CALLBACK (on_treeview_nada_row_activated),
                    NULL);
  g_signal_connect ((gpointer) gotoajnada, "clicked",
                    G_CALLBACK (on_gotoajnada_clicked),
                    NULL);
  g_signal_connect ((gpointer) gotomadifnada, "clicked",
                    G_CALLBACK (on_gotomadifnada_clicked),
                    NULL);
  g_signal_connect ((gpointer) gotosuppr, "clicked",
                    G_CALLBACK (on_gotosuppr_clicked),
                    NULL);
  g_signal_connect ((gpointer) cherchercrenau, "clicked",
                    G_CALLBACK (on_cherchercrenau_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher_nada, "clicked",
                    G_CALLBACK (on_chercher_nada_clicked),
                    NULL);
  g_signal_connect ((gpointer) actutreenada, "clicked",
                    G_CALLBACK (on_actutreenada_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affiche_nada, affiche_nada, "affiche_nada");
  GLADE_HOOKUP_OBJECT (affiche_nada, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (affiche_nada, treeview_nada, "treeview_nada");
  GLADE_HOOKUP_OBJECT (affiche_nada, spinbuttonjaffich, "spinbuttonjaffich");
  GLADE_HOOKUP_OBJECT (affiche_nada, spinbuttonmaffich, "spinbuttonmaffich");
  GLADE_HOOKUP_OBJECT (affiche_nada, spinbuttonaaffich, "spinbuttonaaffich");
  GLADE_HOOKUP_OBJECT (affiche_nada, btnretourm, "btnretourm");
  GLADE_HOOKUP_OBJECT (affiche_nada, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (affiche_nada, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (affiche_nada, image2, "image2");
  GLADE_HOOKUP_OBJECT (affiche_nada, label7, "label7");
  GLADE_HOOKUP_OBJECT (affiche_nada, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (affiche_nada, gotoajnada, "gotoajnada");
  GLADE_HOOKUP_OBJECT (affiche_nada, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (affiche_nada, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (affiche_nada, image3, "image3");
  GLADE_HOOKUP_OBJECT (affiche_nada, label8, "label8");
  GLADE_HOOKUP_OBJECT (affiche_nada, gotomadifnada, "gotomadifnada");
  GLADE_HOOKUP_OBJECT (affiche_nada, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (affiche_nada, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (affiche_nada, image4, "image4");
  GLADE_HOOKUP_OBJECT (affiche_nada, label9, "label9");
  GLADE_HOOKUP_OBJECT (affiche_nada, gotosuppr, "gotosuppr");
  GLADE_HOOKUP_OBJECT (affiche_nada, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (affiche_nada, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (affiche_nada, image5, "image5");
  GLADE_HOOKUP_OBJECT (affiche_nada, label10, "label10");
  GLADE_HOOKUP_OBJECT (affiche_nada, cherchercrenau, "cherchercrenau");
  GLADE_HOOKUP_OBJECT (affiche_nada, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (affiche_nada, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (affiche_nada, image6, "image6");
  GLADE_HOOKUP_OBJECT (affiche_nada, label13, "label13");
  GLADE_HOOKUP_OBJECT (affiche_nada, label11, "label11");
  GLADE_HOOKUP_OBJECT (affiche_nada, comboboxentryafffichnada, "comboboxentryafffichnada");
  GLADE_HOOKUP_OBJECT (affiche_nada, label1, "label1");
  GLADE_HOOKUP_OBJECT (affiche_nada, label2, "label2");
  GLADE_HOOKUP_OBJECT (affiche_nada, label3, "label3");
  GLADE_HOOKUP_OBJECT (affiche_nada, label4, "label4");
  GLADE_HOOKUP_OBJECT (affiche_nada, chercher_nada, "chercher_nada");
  GLADE_HOOKUP_OBJECT (affiche_nada, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (affiche_nada, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (affiche_nada, image1, "image1");
  GLADE_HOOKUP_OBJECT (affiche_nada, label6, "label6");
  GLADE_HOOKUP_OBJECT (affiche_nada, resultatrecherchecrenau, "resultatrecherchecrenau");
  GLADE_HOOKUP_OBJECT (affiche_nada, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (affiche_nada, resultatcherchelab, "resultatcherchelab");
  GLADE_HOOKUP_OBJECT (affiche_nada, actutreenada, "actutreenada");
  GLADE_HOOKUP_OBJECT (affiche_nada, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (affiche_nada, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (affiche_nada, image14, "image14");
  GLADE_HOOKUP_OBJECT (affiche_nada, label48, "label48");

  return affiche_nada;
}

GtkWidget*
create_ajouter_nada (void)
{
  GtkWidget *ajouter_nada;
  GtkWidget *fixed2;
  GtkWidget *label14;
  GtkWidget *entrynomaj;
  GtkWidget *entryprenomaj;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *entryidrdvaj;
  GtkWidget *entrycinaj;
  GtkWidget *label18;
  GtkWidget *entrytelaj;
  GtkWidget *radiobuttonhmaj;
  GSList *radiobuttonhmaj_group = NULL;
  GtkWidget *radiobuttonfemaj;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *label17;
  GtkWidget *label21;
  GtkObject *spinbuttonjaj_adj;
  GtkWidget *spinbuttonjaj;
  GtkObject *spinbuttonmaj_adj;
  GtkWidget *spinbuttonmaj;
  GtkObject *spinbuttonaaj_adj;
  GtkWidget *spinbuttonaaj;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkObject *spinbuttonjpraj_adj;
  GtkWidget *spinbuttonjpraj;
  GtkObject *spinbuttonmpraj_adj;
  GtkWidget *spinbuttonmpraj;
  GtkObject *spinbuttonapraj_adj;
  GtkWidget *spinbuttonapraj;
  GtkWidget *label24;
  GtkWidget *entryidetabaj;
  GtkWidget *retourajtoaffich;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label26;
  GtkWidget *confirmerajnada;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label27;
  GtkWidget *confirmationajnada;
  GtkWidget *comboboxentrycrenaj;
  GtkWidget *comboboxentrytypeaj;

  ajouter_nada = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_nada), _("Ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajouter_nada), fixed2);

  label14 = gtk_label_new (_("Nom"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 40, 40);
  gtk_widget_set_size_request (label14, 49, 17);

  entrynomaj = gtk_entry_new ();
  gtk_widget_show (entrynomaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entrynomaj, 208, 40);
  gtk_widget_set_size_request (entrynomaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomaj), 8226);

  entryprenomaj = gtk_entry_new ();
  gtk_widget_show (entryprenomaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entryprenomaj, 208, 88);
  gtk_widget_set_size_request (entryprenomaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomaj), 8226);

  label15 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 32, 96);
  gtk_widget_set_size_request (label15, 88, 16);

  label16 = gtk_label_new (_("id RDV"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 48, 144);
  gtk_widget_set_size_request (label16, 49, 17);

  entryidrdvaj = gtk_entry_new ();
  gtk_widget_show (entryidrdvaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entryidrdvaj, 208, 136);
  gtk_widget_set_size_request (entryidrdvaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidrdvaj), 8226);

  entrycinaj = gtk_entry_new ();
  gtk_widget_show (entrycinaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entrycinaj, 208, 184);
  gtk_widget_set_size_request (entrycinaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinaj), 8226);

  label18 = gtk_label_new (_("telephone"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 32, 240);
  gtk_widget_set_size_request (label18, 96, 16);

  entrytelaj = gtk_entry_new ();
  gtk_widget_show (entrytelaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entrytelaj, 208, 232);
  gtk_widget_set_size_request (entrytelaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytelaj), 8226);

  radiobuttonhmaj = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobuttonhmaj);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonhmaj, 208, 280);
  gtk_widget_set_size_request (radiobuttonhmaj, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonhmaj), radiobuttonhmaj_group);
  radiobuttonhmaj_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonhmaj));

  radiobuttonfemaj = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonfemaj);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonfemaj, 360, 280);
  gtk_widget_set_size_request (radiobuttonfemaj, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemaj), radiobuttonhmaj_group);
  radiobuttonhmaj_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemaj));

  label20 = gtk_label_new (_("Date Render-Vous"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed2), label20, 24, 336);
  gtk_widget_set_size_request (label20, 160, 16);

  label19 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 40, 288);
  gtk_widget_set_size_request (label19, 49, 17);

  label17 = gtk_label_new (_("Cin"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 32, 192);
  gtk_widget_set_size_request (label17, 49, 17);

  label21 = gtk_label_new (_("Creneau horaire"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 24, 384);
  gtk_widget_set_size_request (label21, 136, 16);

  spinbuttonjaj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjaj_adj), 1, 0);
  gtk_widget_show (spinbuttonjaj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonjaj, 208, 328);
  gtk_widget_set_size_request (spinbuttonjaj, 60, 27);

  spinbuttonmaj_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmaj_adj), 1, 0);
  gtk_widget_show (spinbuttonmaj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonmaj, 280, 328);
  gtk_widget_set_size_request (spinbuttonmaj, 60, 27);

  spinbuttonaaj_adj = gtk_adjustment_new (1970, 1970, 2024, 1, 10, 10);
  spinbuttonaaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonaaj_adj), 1, 0);
  gtk_widget_show (spinbuttonaaj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonaaj, 360, 328);
  gtk_widget_set_size_request (spinbuttonaaj, 60, 27);

  label22 = gtk_label_new (_("Type de sang"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 8, 440);
  gtk_widget_set_size_request (label22, 144, 16);

  label23 = gtk_label_new (_("Date premier Render-Vous"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 16, 504);
  gtk_widget_set_size_request (label23, 224, 24);

  spinbuttonjpraj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjpraj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjpraj_adj), 1, 0);
  gtk_widget_show (spinbuttonjpraj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonjpraj, 240, 504);
  gtk_widget_set_size_request (spinbuttonjpraj, 60, 27);

  spinbuttonmpraj_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmpraj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmpraj_adj), 1, 0);
  gtk_widget_show (spinbuttonmpraj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonmpraj, 312, 504);
  gtk_widget_set_size_request (spinbuttonmpraj, 60, 27);

  spinbuttonapraj_adj = gtk_adjustment_new (1970, 1970, 2024, 1, 10, 10);
  spinbuttonapraj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonapraj_adj), 1, 0);
  gtk_widget_show (spinbuttonapraj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonapraj, 384, 504);
  gtk_widget_set_size_request (spinbuttonapraj, 60, 27);

  label24 = gtk_label_new (_("Id etablissement"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 8, 568);
  gtk_widget_set_size_request (label24, 176, 16);

  entryidetabaj = gtk_entry_new ();
  gtk_widget_show (entryidetabaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entryidetabaj, 208, 560);
  gtk_widget_set_size_request (entryidetabaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidetabaj), 8226);

  retourajtoaffich = gtk_button_new ();
  gtk_widget_show (retourajtoaffich);
  gtk_fixed_put (GTK_FIXED (fixed2), retourajtoaffich, 40, 664);
  gtk_widget_set_size_request (retourajtoaffich, 80, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (retourajtoaffich), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox7), label26, FALSE, FALSE, 0);

  confirmerajnada = gtk_button_new ();
  gtk_widget_show (confirmerajnada);
  gtk_fixed_put (GTK_FIXED (fixed2), confirmerajnada, 272, 664);
  gtk_widget_set_size_request (confirmerajnada, 120, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (confirmerajnada), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox8), label27, FALSE, FALSE, 0);

  confirmationajnada = gtk_label_new ("");
  gtk_widget_show (confirmationajnada);
  gtk_fixed_put (GTK_FIXED (fixed2), confirmationajnada, 56, 600);
  gtk_widget_set_size_request (confirmationajnada, 400, 32);

  comboboxentrycrenaj = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrycrenaj);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentrycrenaj, 208, 376);
  gtk_widget_set_size_request (comboboxentrycrenaj, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenaj), _("9h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenaj), _("11h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenaj), _("13h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenaj), _("14h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenaj), _("15h"));

  comboboxentrytypeaj = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrytypeaj);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentrytypeaj, 208, 432);
  gtk_widget_set_size_request (comboboxentrytypeaj, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypeaj), _("A+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypeaj), _("A-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypeaj), _("O+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypeaj), _("O-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypeaj), _("B+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypeaj), _("B-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypeaj), _("AB+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypeaj), _("AB-"));

  g_signal_connect ((gpointer) radiobuttonhmaj, "toggled",
                    G_CALLBACK (on_radiobuttonhmaj_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonfemaj, "toggled",
                    G_CALLBACK (on_radiobuttonfemaj_toggled),
                    NULL);
  g_signal_connect ((gpointer) retourajtoaffich, "clicked",
                    G_CALLBACK (on_retourajtoaffich_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmerajnada, "clicked",
                    G_CALLBACK (on_confirmerajnada_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_nada, ajouter_nada, "ajouter_nada");
  GLADE_HOOKUP_OBJECT (ajouter_nada, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajouter_nada, entrynomaj, "entrynomaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, entryprenomaj, "entryprenomaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label16, "label16");
  GLADE_HOOKUP_OBJECT (ajouter_nada, entryidrdvaj, "entryidrdvaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, entrycinaj, "entrycinaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label18, "label18");
  GLADE_HOOKUP_OBJECT (ajouter_nada, entrytelaj, "entrytelaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, radiobuttonhmaj, "radiobuttonhmaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, radiobuttonfemaj, "radiobuttonfemaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label20, "label20");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label19, "label19");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label21, "label21");
  GLADE_HOOKUP_OBJECT (ajouter_nada, spinbuttonjaj, "spinbuttonjaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, spinbuttonmaj, "spinbuttonmaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, spinbuttonaaj, "spinbuttonaaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label22, "label22");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label23, "label23");
  GLADE_HOOKUP_OBJECT (ajouter_nada, spinbuttonjpraj, "spinbuttonjpraj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, spinbuttonmpraj, "spinbuttonmpraj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, spinbuttonapraj, "spinbuttonapraj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label24, "label24");
  GLADE_HOOKUP_OBJECT (ajouter_nada, entryidetabaj, "entryidetabaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, retourajtoaffich, "retourajtoaffich");
  GLADE_HOOKUP_OBJECT (ajouter_nada, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajouter_nada, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajouter_nada, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label26, "label26");
  GLADE_HOOKUP_OBJECT (ajouter_nada, confirmerajnada, "confirmerajnada");
  GLADE_HOOKUP_OBJECT (ajouter_nada, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ajouter_nada, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajouter_nada, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajouter_nada, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajouter_nada, confirmationajnada, "confirmationajnada");
  GLADE_HOOKUP_OBJECT (ajouter_nada, comboboxentrycrenaj, "comboboxentrycrenaj");
  GLADE_HOOKUP_OBJECT (ajouter_nada, comboboxentrytypeaj, "comboboxentrytypeaj");

  return ajouter_nada;
}

GtkWidget*
create_modifier_nada (void)
{
  GtkWidget *modifier_nada;
  GtkWidget *fixed3;
  GtkWidget *entrynommodif;
  GtkWidget *entryprenommodf;
  GtkWidget *entryidrmodif;
  GtkWidget *entrycinmodif;
  GtkWidget *label31;
  GtkWidget *entrytelephonemodif;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkObject *spinbuttonjrmodif_adj;
  GtkWidget *spinbuttonjrmodif;
  GtkObject *spinbuttonmrmodif_adj;
  GtkWidget *spinbuttonmrmodif;
  GtkObject *spinbuttonarmodif_adj;
  GtkWidget *spinbuttonarmodif;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkObject *spinbuttonjdateprmodif_adj;
  GtkWidget *spinbuttonjdateprmodif;
  GtkObject *spinbuttonmprmodif_adj;
  GtkWidget *spinbuttonmprmodif;
  GtkObject *spinbuttonaprmodif_adj;
  GtkWidget *spinbuttonaprmodif;
  GtkWidget *label38;
  GtkWidget *entryidetabmodif;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *recherchermodif;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label42;
  GtkWidget *resultatrecherchemodif;
  GtkWidget *radiobuttonhommodif;
  GSList *radiobuttonhommodif_group = NULL;
  GtkWidget *radiobuttonfemmodif;
  GtkWidget *comboboxentrycrenmodif;
  GtkWidget *comboboxentrytypesang;
  GtkWidget *gotoaffichonmodif;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label39;
  GtkWidget *resultatmodif;
  GtkWidget *confirmodifna;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label40;

  modifier_nada = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_nada), _("Modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier_nada), fixed3);

  entrynommodif = gtk_entry_new ();
  gtk_widget_show (entrynommodif);
  gtk_fixed_put (GTK_FIXED (fixed3), entrynommodif, 208, 88);
  gtk_widget_set_size_request (entrynommodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynommodif), 8226);

  entryprenommodf = gtk_entry_new ();
  gtk_widget_show (entryprenommodf);
  gtk_fixed_put (GTK_FIXED (fixed3), entryprenommodf, 208, 136);
  gtk_widget_set_size_request (entryprenommodf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenommodf), 8226);

  entryidrmodif = gtk_entry_new ();
  gtk_widget_show (entryidrmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), entryidrmodif, 136, 16);
  gtk_widget_set_size_request (entryidrmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidrmodif), 8226);

  entrycinmodif = gtk_entry_new ();
  gtk_widget_show (entrycinmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), entrycinmodif, 208, 184);
  gtk_widget_set_size_request (entrycinmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinmodif), 8226);

  label31 = gtk_label_new (_("telephone"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed3), label31, 32, 240);
  gtk_widget_set_size_request (label31, 96, 16);

  entrytelephonemodif = gtk_entry_new ();
  gtk_widget_show (entrytelephonemodif);
  gtk_fixed_put (GTK_FIXED (fixed3), entrytelephonemodif, 208, 232);
  gtk_widget_set_size_request (entrytelephonemodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytelephonemodif), 8226);

  label32 = gtk_label_new (_("Date Render-Vous"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed3), label32, 24, 336);
  gtk_widget_set_size_request (label32, 160, 16);

  label33 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed3), label33, 40, 288);
  gtk_widget_set_size_request (label33, 49, 17);

  label34 = gtk_label_new (_("Cin"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed3), label34, 32, 192);
  gtk_widget_set_size_request (label34, 49, 17);

  label35 = gtk_label_new (_("Creneau horaire"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed3), label35, 24, 384);
  gtk_widget_set_size_request (label35, 136, 16);

  spinbuttonjrmodif_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjrmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjrmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonjrmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonjrmodif, 208, 328);
  gtk_widget_set_size_request (spinbuttonjrmodif, 60, 27);

  spinbuttonmrmodif_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmrmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmrmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonmrmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonmrmodif, 280, 328);
  gtk_widget_set_size_request (spinbuttonmrmodif, 60, 27);

  spinbuttonarmodif_adj = gtk_adjustment_new (1970, 1970, 2024, 1, 10, 10);
  spinbuttonarmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonarmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonarmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonarmodif, 360, 328);
  gtk_widget_set_size_request (spinbuttonarmodif, 60, 27);

  label36 = gtk_label_new (_("Type de sang"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed3), label36, 8, 440);
  gtk_widget_set_size_request (label36, 144, 16);

  label37 = gtk_label_new (_("Date premier Render-Vous"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed3), label37, 16, 504);
  gtk_widget_set_size_request (label37, 224, 24);

  spinbuttonjdateprmodif_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjdateprmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjdateprmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonjdateprmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonjdateprmodif, 240, 504);
  gtk_widget_set_size_request (spinbuttonjdateprmodif, 60, 27);

  spinbuttonmprmodif_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmprmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmprmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonmprmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonmprmodif, 312, 504);
  gtk_widget_set_size_request (spinbuttonmprmodif, 60, 27);

  spinbuttonaprmodif_adj = gtk_adjustment_new (1970, 1970, 2024, 1, 10, 10);
  spinbuttonaprmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonaprmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonaprmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonaprmodif, 384, 504);
  gtk_widget_set_size_request (spinbuttonaprmodif, 60, 27);

  label38 = gtk_label_new (_("Id etablissement"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed3), label38, 8, 568);
  gtk_widget_set_size_request (label38, 176, 16);

  entryidetabmodif = gtk_entry_new ();
  gtk_widget_show (entryidetabmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), entryidetabmodif, 208, 560);
  gtk_widget_set_size_request (entryidetabmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidetabmodif), 8226);

  label28 = gtk_label_new (_("Nom"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 48, 96);
  gtk_widget_set_size_request (label28, 49, 17);

  label29 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 32, 144);
  gtk_widget_set_size_request (label29, 88, 16);

  label30 = gtk_label_new (_("id RDV"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 64, 24);
  gtk_widget_set_size_request (label30, 49, 17);

  recherchermodif = gtk_button_new ();
  gtk_widget_show (recherchermodif);
  gtk_fixed_put (GTK_FIXED (fixed3), recherchermodif, 336, 16);
  gtk_widget_set_size_request (recherchermodif, 104, 24);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (recherchermodif), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox11), label42, FALSE, FALSE, 0);

  resultatrecherchemodif = gtk_label_new ("");
  gtk_widget_show (resultatrecherchemodif);
  gtk_fixed_put (GTK_FIXED (fixed3), resultatrecherchemodif, 88, 48);
  gtk_widget_set_size_request (resultatrecherchemodif, 312, 32);

  radiobuttonhommodif = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonhommodif);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonhommodif, 208, 288);
  gtk_widget_set_size_request (radiobuttonhommodif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonhommodif), radiobuttonhommodif_group);
  radiobuttonhommodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonhommodif));

  radiobuttonfemmodif = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonfemmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonfemmodif, 352, 288);
  gtk_widget_set_size_request (radiobuttonfemmodif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemmodif), radiobuttonhommodif_group);
  radiobuttonhommodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemmodif));

  comboboxentrycrenmodif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrycrenmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentrycrenmodif, 208, 376);
  gtk_widget_set_size_request (comboboxentrycrenmodif, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenmodif), _("9h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenmodif), _("11h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenmodif), _("13h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenmodif), _("14h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrycrenmodif), _("15h"));

  comboboxentrytypesang = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrytypesang);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentrytypesang, 208, 432);
  gtk_widget_set_size_request (comboboxentrytypesang, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypesang), _("A+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypesang), _("A-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypesang), _("O+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypesang), _("O-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypesang), _("B+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypesang), _("B-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypesang), _("AB+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrytypesang), _("AB-"));

  gotoaffichonmodif = gtk_button_new ();
  gtk_widget_show (gotoaffichonmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), gotoaffichonmodif, 40, 664);
  gtk_widget_set_size_request (gotoaffichonmodif, 80, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (gotoaffichonmodif), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox9), label39, FALSE, FALSE, 0);

  resultatmodif = gtk_label_new ("");
  gtk_widget_show (resultatmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), resultatmodif, 56, 600);
  gtk_widget_set_size_request (resultatmodif, 400, 32);

  confirmodifna = gtk_button_new ();
  gtk_widget_show (confirmodifna);
  gtk_fixed_put (GTK_FIXED (fixed3), confirmodifna, 272, 664);
  gtk_widget_set_size_request (confirmodifna, 120, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (confirmodifna), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox10), label40, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) recherchermodif, "clicked",
                    G_CALLBACK (on_recherchermodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonhommodif, "toggled",
                    G_CALLBACK (on_radiobuttonhommodif_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonfemmodif, "toggled",
                    G_CALLBACK (on_radiobuttonfemmodif_toggled),
                    NULL);
  g_signal_connect ((gpointer) gotoaffichonmodif, "clicked",
                    G_CALLBACK (on_gotoaffichonmodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmodifna, "clicked",
                    G_CALLBACK (on_confirmodifna_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_nada, modifier_nada, "modifier_nada");
  GLADE_HOOKUP_OBJECT (modifier_nada, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier_nada, entrynommodif, "entrynommodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, entryprenommodf, "entryprenommodf");
  GLADE_HOOKUP_OBJECT (modifier_nada, entryidrmodif, "entryidrmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, entrycinmodif, "entrycinmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, label31, "label31");
  GLADE_HOOKUP_OBJECT (modifier_nada, entrytelephonemodif, "entrytelephonemodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, label32, "label32");
  GLADE_HOOKUP_OBJECT (modifier_nada, label33, "label33");
  GLADE_HOOKUP_OBJECT (modifier_nada, label34, "label34");
  GLADE_HOOKUP_OBJECT (modifier_nada, label35, "label35");
  GLADE_HOOKUP_OBJECT (modifier_nada, spinbuttonjrmodif, "spinbuttonjrmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, spinbuttonmrmodif, "spinbuttonmrmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, spinbuttonarmodif, "spinbuttonarmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, label36, "label36");
  GLADE_HOOKUP_OBJECT (modifier_nada, label37, "label37");
  GLADE_HOOKUP_OBJECT (modifier_nada, spinbuttonjdateprmodif, "spinbuttonjdateprmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, spinbuttonmprmodif, "spinbuttonmprmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, spinbuttonaprmodif, "spinbuttonaprmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, label38, "label38");
  GLADE_HOOKUP_OBJECT (modifier_nada, entryidetabmodif, "entryidetabmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, label28, "label28");
  GLADE_HOOKUP_OBJECT (modifier_nada, label29, "label29");
  GLADE_HOOKUP_OBJECT (modifier_nada, label30, "label30");
  GLADE_HOOKUP_OBJECT (modifier_nada, recherchermodif, "recherchermodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (modifier_nada, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (modifier_nada, image11, "image11");
  GLADE_HOOKUP_OBJECT (modifier_nada, label42, "label42");
  GLADE_HOOKUP_OBJECT (modifier_nada, resultatrecherchemodif, "resultatrecherchemodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, radiobuttonhommodif, "radiobuttonhommodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, radiobuttonfemmodif, "radiobuttonfemmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, comboboxentrycrenmodif, "comboboxentrycrenmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, comboboxentrytypesang, "comboboxentrytypesang");
  GLADE_HOOKUP_OBJECT (modifier_nada, gotoaffichonmodif, "gotoaffichonmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier_nada, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier_nada, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier_nada, label39, "label39");
  GLADE_HOOKUP_OBJECT (modifier_nada, resultatmodif, "resultatmodif");
  GLADE_HOOKUP_OBJECT (modifier_nada, confirmodifna, "confirmodifna");
  GLADE_HOOKUP_OBJECT (modifier_nada, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier_nada, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modifier_nada, image10, "image10");
  GLADE_HOOKUP_OBJECT (modifier_nada, label40, "label40");

  return modifier_nada;
}

GtkWidget*
create_supprimer_nada (void)
{
  GtkWidget *supprimer_nada;
  GtkWidget *fixed4;
  GtkWidget *label44;
  GtkWidget *entryidsupp;
  GtkWidget *resultatsupp;
  GtkWidget *gotomenuonsupp;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label46;
  GtkWidget *suppnada;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label47;

  supprimer_nada = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_nada), _("Supprimer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprimer_nada), fixed4);

  label44 = gtk_label_new (_("Id RDV"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 40, 64);
  gtk_widget_set_size_request (label44, 49, 17);

  entryidsupp = gtk_entry_new ();
  gtk_widget_show (entryidsupp);
  gtk_fixed_put (GTK_FIXED (fixed4), entryidsupp, 136, 64);
  gtk_widget_set_size_request (entryidsupp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidsupp), 8226);

  resultatsupp = gtk_label_new ("");
  gtk_widget_show (resultatsupp);
  gtk_fixed_put (GTK_FIXED (fixed4), resultatsupp, 40, 112);
  gtk_widget_set_size_request (resultatsupp, 320, 48);

  gotomenuonsupp = gtk_button_new ();
  gtk_widget_show (gotomenuonsupp);
  gtk_fixed_put (GTK_FIXED (fixed4), gotomenuonsupp, 16, 216);
  gtk_widget_set_size_request (gotomenuonsupp, 74, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (gotomenuonsupp), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox12), label46, FALSE, FALSE, 0);

  suppnada = gtk_button_new ();
  gtk_widget_show (suppnada);
  gtk_fixed_put (GTK_FIXED (fixed4), suppnada, 192, 216);
  gtk_widget_set_size_request (suppnada, 128, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (suppnada), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox13), label47, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) gotomenuonsupp, "clicked",
                    G_CALLBACK (on_gotomenuonsupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) suppnada, "clicked",
                    G_CALLBACK (on_suppnada_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_nada, supprimer_nada, "supprimer_nada");
  GLADE_HOOKUP_OBJECT (supprimer_nada, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprimer_nada, label44, "label44");
  GLADE_HOOKUP_OBJECT (supprimer_nada, entryidsupp, "entryidsupp");
  GLADE_HOOKUP_OBJECT (supprimer_nada, resultatsupp, "resultatsupp");
  GLADE_HOOKUP_OBJECT (supprimer_nada, gotomenuonsupp, "gotomenuonsupp");
  GLADE_HOOKUP_OBJECT (supprimer_nada, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (supprimer_nada, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (supprimer_nada, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer_nada, label46, "label46");
  GLADE_HOOKUP_OBJECT (supprimer_nada, suppnada, "suppnada");
  GLADE_HOOKUP_OBJECT (supprimer_nada, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (supprimer_nada, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (supprimer_nada, image13, "image13");
  GLADE_HOOKUP_OBJECT (supprimer_nada, label47, "label47");

  return supprimer_nada;
}

