/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_affiche_nada (void);
GtkWidget* create_ajouter_nada (void);
GtkWidget* create_modifier_nada (void);
GtkWidget* create_supprimer_nada (void);
